.github/workflows/on_pull_request.yml
-
-
Before | After
:--: | :--:
=> Hotfix for github actions

.travis/android/script.bash
- For fixing dynamic feature module crashes
-
Before | After
:--: | :--:
=> Use aab for uploading deploy gate

.travis/android/script.bash
Reverts DroidKaigi/conference-app-2020#213
It does not work 😭
=> Revert "Use aab for uploading deploy gate"

README.md
- No Number
- fix broken link on read me
- https://developer.android.com/studio/preview
Before | After
:--: | :--:
=> Fix broken link of README

feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt, feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/item/DividerItem.kt, feature/sponsor/src/main/res/layout/fragment_sponsors.xml, feature/sponsor/src/main/res/layout/item_divider.xml, feature/sponsor/src/main/res/layout/item_sponsor.xml, feature/sponsor/src/main/res/layout/item_sponsor_large.xml, model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SponsorCategory.kt
- close #29 
- Apply figma design about sponsor screen.
- Change margin and add divider item in last section index.
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=0%3A1
=> Apply sponsor design

feature/session/src/main/res/layout/fragment_main_sessions.xml
- close #199 
- close #128 
- Added margin to TabLayout.  
- Changed ripple effect when tap tab item.
- Fixed around TabLayout color when DarkTheme.  
-
Before | After
:--: | :--:
=> Fixed TabLayout design

android-base/build.gradle, android-base/src/debug/java/io/github/droidkaigi/confsched2020/DebugApp.kt, build.gradle, buildSrc/src/main/java/dependencies/Dep.kt
- close #182 
- add crashlytics settings
-
Before | After
:--: | :--:
=> add Firebase Crashlytics

README.md, buildSrc/src/main/java/dependencies/Dep.kt, corecomponent/androidcomponent/build.gradle
- close #143 
- remove Shopify's livedata-ktx that is in Readme, Dep,ktx , corecomponent\androidcomponent\build.gradle
=> remove shopify's livedata-ktx dependency

feature/session/src/main/res/layout/fragment_session_detail.xml, model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Session.kt
- close #167 
- add lang judge shortSummary() -> shortSummary(lang)
- 
Before | After
:--: | :--:
=> #167 Fix LocaledString in session detail

android-base/src/debug/java/io/github/droidkaigi/confsched2020/DebugApp.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt, corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/CoordinatorLayoutInViewPagerHost.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetDaySessionsFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
=> Apply "Redundant" item among Lint results

README.md
- N/A
- Fix typo (Mutidex -> Multidex) 🙇 
- https://developer.android.com/jetpack/
- N/A
=> Fix typo (Mutidex -> Multidex)

corecomponent/androidcomponent/src/main/res/values/strings.xml
- close #170
-Change "error_unknown" messages value in corecomponent/androidcomponent/src/main/res/values/strings.xml
"Error unknown" to "Connection attempt failed.Please try again."
-https://github.com/felix925/conference-app-2020/blob/master/corecomponent/androidcomponent/src/main/res/values/strings.xml#42
=> #170 Change to an easy-to-understand error message

android-base/src/main/AndroidManifest.xml, corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
- close #146
- Add DeepLinks Setting
- https://medium.com/@star_zero/navigation%E3%81%AEimplicit-deep-link%E8%A9%B3%E7%B4%B0-1e2d955f41ae
None
=> Fix #146 Add deep-link support Announcement

data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/parameter/LangParameter.kt
- close #258 
- Fix the endpoint parameter
- Nothing
Before | After
:--: | :--:
=> Fix Lang parameter value

feature/session/src/main/res/layout/layout_speaker.xml
- close #131 
- Add tap feedback to LinearLayout of item_speaker.xml
-
| SessionDetail | Sessions |
|:---:|:---:|
| <img src="https://user-images.githubusercontent.com/4950792/72428483-249a3580-37d1-11ea-9353-8293a05ba47f.png" width="300" /> | <img src="https://user-images.githubusercontent.com/4950792/72428678-8bb7ea00-37d1-11ea-9da2-5c44de66193a.png" width="300" /> |
=> Add tap feedback to LinearLayout of item_speaker.xml

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt
- close https://github.com/DroidKaigi/conference-app-2020/issues/129
- Add named argument
=> Add named argument for StartTimeText

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt, feature/session/src/main/res/color-night/search_close_icon.xml, feature/session/src/main/res/color-night/search_icon.xml, feature/session/src/main/res/color/search_close_icon.xml, feature/session/src/main/res/color/search_icon.xml
- close https://github.com/DroidKaigi/conference-app-2020/issues/113
- change icon( search btn and close btn) color on SerachView
- ref : https://stackoverflow.com/questions/44855532/how-to-change-searchview-icon-color
Before | After
:--: | :--:
=> Change icon color on SerachView

data/api/src/iosMain/kotlin/io/github/droidkaigi/confsched2020/data/api/ApiComponent.kt, data/api/src/main/java/io/github/droidkaigi/confsched2020/data/api/internal/UserAgentInterceptor.kt
- N/A
- Change UserAgent from 2019 to 2020
- N/A
- N/A
=> Change UserAgent from 2019 to 2020

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
- close #267
- Added Ripple Effect to expandLess Layout.
- Adjusted view size so that the effect is applied properly.
- N/A
Before | After
:--: | :--:
=> Added ripple effect to BottomSheet expand icon

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt, feature/session/src/main/res/menu/menu_session_detail_bottomappbar.xml
- close #162
- Add a link from the BottomAppBar in the session details to the floor map
- N/A
Before | After
:--: | :--:
=> Add a link from the BottomAppBar in the session details to the floor map

.travis/android/script.bash
- close #217
- Create universal apk for fixing issue
- 🙏 
-
Before | After
:--: | :--:
=> Try to create universal apk

feature/sponsor/src/test/java/io/github/droidkaigi/confsched2020/sponsor/ui/viewmodel/Dummies.kt, feature/sponsor/src/test/java/io/github/droidkaigi/confsched2020/sponsor/ui/viewmodel/SponsorsViewModelTest.kt
- close #158 
- add SponsorsViewModelTest in sponsor module
=> add SponsorsViewModel test

.travis/android/script.bash
- 🙏 
-
Before | After
:--: | :--:
=> Try to create universal apk2

.travis/android/script.bash
- 🙏 
-
Before | After
:--: | :--:
=> Try to create universal apk3

.travis/android/script.bash
- 🙏 
-
Before | After
:--: | :--:
=> Try to create universal apk4

feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SpeakerViewModelTest.kt
- happy case
- specified non-exists speakerId case
- sessionContents empty case
- close #157
=> implement test for SpeakerViewModel

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt
- close #202 
- use forEachIndexed
- remove `lastStartTimeText` and get last session each loop
Before | After
:--: | :--:
=> Fix blink when favorite

feature/preference/src/main/java/io/github/droidkaigi/confsched2020/preference/ui/PreferencesFragment.kt
- N/A
- Remove unnecessary parentheses
- N/A
- N/A
=> Remove unnecessary parentheses

android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt
- N/A
- Changed to use property access syntax
- N/A
- N/A
=> Fix warning : Use property access syntax

README.md, android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt, feature/session/src/main/res/layout/fragment_sessions.xml, model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/ContributorContents.kt
- N/A
- prodution -> production
- occured -> occurred
- fragment_sessions_coodinator -> fragment_sessions_coordinator
- EMTPY -> EMPTY
N/A
N/A
=> Fix typo (e.g. prodution -> production)

feature/session/src/main/res/layout/fragment_speaker.xml
- #297 
Title says it all.
N/A
before | after
---- | ----
=> Speaker Session Name not showing multiple lines in TextView

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
- close #301
- just only removed FrameLayout.
Review just only 606ce5c .
Nothing changed.
Before | After
:--: | :--:
=> Optimize layout 

feature/announcement/src/test/java/io/github/droidkaigi/confsched2020/announcement/ui/viewmodel/AnnouncementViewModelTest.kt, feature/announcement/src/test/java/io/github/droidkaigi/confsched2020/announcement/ui/viewmodel/Dummies.kt
- #159 
- add AnnouncementViewModelTest in announcement module
=> implement test for AnnouncementViewModel

.github/workflows/on_pull_request.yml
- close #255
Fix-Gem cache not stored
https://github.com/DroidKaigi/conference-app-2020/compare/master...Takafumi-Orita:Fix_ci?expand=1#diff-3e808f84fba6a3eccf009fc20119d00d
=> Gem cache not stored.

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
fix issue #126
- close #126 
- handle back button pressed with OnBackPressedDispatcher
- handle event only if filter appeared (front layer collapsed) because if callback always enabled we cannot back to home 😢 
- it's my first time to use OnBackPressedDispatcher so I'm glad to tell me if you know how to pass back-button pressed event to default behavior
- https://developer.android.com/guide/navigation/navigation-custom-back
Before | After
:--: | :--:
=> Expand front layer when back button pressed

LICENSE
- None
We should fill out year and name in  License file.
I referenced ↓
- https://github.com/JetBrains/kotlin/blob/master/license/LICENSE.txt#L190
=> Add year and organization name

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt, corecomponent/androidtestcomponent/src/main/java/io/github/droidkaigi/confsched2020/widget/component/CoroutinesRule.kt, corecomponent/androidtestcomponent/src/main/java/io/github/droidkaigi/confsched2020/widget/component/MockkRule.kt, data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/internal/KtorDroidKaigiApi.kt, data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/internal/KtorGoogleFormApi.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerItem.kt
- N/A
- Run Inspect Code ▶ Style issues ▶ Class member can have 'private' visibility
- Modify accessor of public to private 🚮 
- Extension Function
- Class member
- Dep.kt
- FilterChip.kt
=> Modify accessor of public to private

corecomponent/androidcomponent/src/main/res/navigation/navigation.xml, data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/internal/KtorDroidKaigiApi.kt, feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt, feature/about/src/main/res/layout/fragment_about.xml
=> Add staffs screen to about for debug

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerDetailItem.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerSessionItem.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SpeakerViewModel.kt, feature/session/src/main/res/layout/fragment_speaker.xml, feature/session/src/main/res/layout/item_speaker_detail.xml, feature/session/src/main/res/layout/item_speaker_session.xml, feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SpeakerViewModelTest.kt
- close #317
- changed SpeakerFragment to implemented it by RecyclerView for supporting multiple sections.
- added two Groupie's item classes, SpeakerDetailItem and SpeakerSessionItem.
Before | After
:--: | :--:
=> Support speaker who has multiple sections by the speaker screen.

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
- close #151 
- During 2020/02/21, fixed to select tab of day 2 
- nothing
- nothing
=> open day2 tab during DroidKaigi second date

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/binding/Bindings.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt, feature/session/src/main/res/layout/fragment_bottom_sheet_favorite_session.xml, feature/session/src/main/res/values-jp/strings.xml, feature/session/src/main/res/values/strings.xml
- close #116
- Add emptyView in my favorite sessions.
- Create some ViewBindings for hiding and showing views with animation. (These animations are not required, so if I should remove them, I'm willing to remove them.)
- Add string resources english ver. and Japanese ver. English ver is write by myself, so Could I ask you 
to check this carefully ?
- None
Before | After(jp) | After(en)
:--: | :--: | :--:
=> Add emptyView in my favorite sessions screen

feature/contributor/src/main/AndroidManifest.xml, feature/preference/src/main/AndroidManifest.xml, feature/staff/src/main/AndroidManifest.xml
- Use new manifest format in dfm
- https://developer.android.com/guide/app-bundle/dynamic-delivery
Before | After
:--: | :--:
=> Use new manifest format in dfm

model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionPage.kt
- close #376
- add space.
- 
Before | After
:--: | :--:
=> Add white spaces to tab labels

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/AutoClearedValue.kt
- none
- The title says everything.
- none
none
=> I think no need to hold and publish fragment field.

ios-base/DroidKaigi 2020.xcodeproj/project.pbxproj
- N/A
- Add Xcode Build Phase to Build Kotlin Modules
-
Before | After
:--: | :--:
=> Add iOS Build Phase to Build Kotlin Modules

corecomponent/androidcomponent/src/main/res/values/strings.xml
- DarkTheme → Dark theme
- Changed to document spelling
- https://material.io/design/color/dark-theme.html#
- https://developer.android.com/guide/topics/ui/look-and-feel/darktheme?hl=en
Before | After
:--: | :--:
=> Cancel camel case

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/binding/Bindings.kt, feature/session/src/main/res/layout/fragment_bottom_sheet_favorite_session.xml
- close #413 
- Make view binding isHide to isInvisible
-
I did not modified.
Before | After
:--: | :--:
=> isHide to isInvisible

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/binding/Bindings.kt, corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/FilterChip.kt, corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/AndroidRTypeAlias.kt, corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/AppcompatRTypeAlias.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt
- close #359 
- Add typealias for R class
- Use typealias for R class
-
These screenshots show all the matching text `.R.`.
Before | After
:--: | :--:
=> Use typealias for R class

corecomponent/androidcomponent/build.gradle, corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ui/ChromeCustomTabsNavigator.kt
- close #402 
- Add try-catch when launchUrl()
-
=> Add try-catch

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt, feature/session/src/main/res/layout/fragment_session_detail.xml
- close #443 
- Title says everything 😃 
- Related to #429
Before | After
:--: | :--:
=> Remove button of session's feedback in session detail screen

feature/staff/build.gradle, feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/StaffsFragment.kt, feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/viewmodel/StaffsViewModel.kt
- close #360 
- use UiModel for StaffsViewModel
- observe it at StaffsFragment
-
=> Use uimodel for staffs viewmodel

.github/workflows/on_release_branch.yml, README.md
- close #462 
- Replaced it with GitHub Actions badge
- The current project always fails because of lint issues
-
Before | After
:--: | :--:
=> Revised a CI badge in README.md

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
none
- Apply review comments on #469
When apply review comments, two issues appear. 
- When click favorite session button, entire screen show fade in effect.
- When click favorite session button, opened session description is closed.
To resolve first problem, I use ItemAnimator (supportsChangeAnimations = false). But I can not resolve it. Second problem needs time to understand implementation. So could someone fix in other PR or tell me how to fix it ?
=> Apply review comments on #469 (Misuse groupie on SessionDetailFragment)

.ci/danger/static_analysis.Dangerfile
- N/A
- Issues that relate to only modified *lines* should be reported but haven't. I'm sorry.
-
Before | After
:--: | :--:
=> Don't report errors and warnings that are annoying us

ios-base/DroidKaigi 2020/Session/ViewModels/SessionViewModel.swift, ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewDataSource.swift
- N/A
- Embdded -> Embedded
- Elememt -> Elememt
- none
- none
=> Fix type (Embdded, Elememt)

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
- close #500 #506
- add clearfocus
- override OnCloseListener
-
Before | After
:--: | :--:
=> Fix SearchView behavior

data/api/build.gradle, data/api/src/iosMain/kotlinDebug/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt, data/api/src/iosMain/kotlinRelease/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt
- close #532
- try it
-
Before | After
:--: | :--:
=> Use http for api

feature/contributor/build.gradle, feature/contributor/src/test/java/io/github/droidkaigi/confsched2020/contributor/ui/viewmodel/ContributorsViewModelTest.kt, feature/contributor/src/test/java/io/github/droidkaigi/confsched2020/contributor/ui/viewmodel/Dummies.kt
- Close #160 
- Added test for ContributorsViewModel
=> 160: Add test for ContributorsViewModel

ios-base/.swiftformat, ios-base/DroidKaigi 2020/AppDelegate.swift, ios-base/DroidKaigi 2020/ApplicationScheme.swift, ios-base/DroidKaigi 2020/SceneDelegate.swift, ios-base/DroidKaigi 2020/Session/ViewModels/SessionViewModel.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift, ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionPageViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewDataSource.swift, ios-base/DroidKaigi 2020/Session/Views/ShapedShadowedView.swift, ios-base/DroidKaigi 2020/Session/Views/SuggestView.swift, ios-base/DroidKaigi 2020Tests/DroidKaigi_2020Tests.swift, ios-base/DroidKaigi 2020UITests/DroidKaigi_2020UITests.swift, ios-base/Mintfile, ios-base/project.yml, ios-base/scripts/format.sh
- None
- Introduce SwiftFormat for good development
- Added minimum rules for now, so feel free to modify it
- Referred #521 to create this PR, thanks @yuta24!
- https://github.com/nicklockwood/SwiftFormat
- https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md
Before | After
:--: | :--:
=> Introduce SwiftFormat

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt, feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
- close #559 
- Change divider shadow visibility
- Change divider width
-
=> Adjust the shadow at session list top 

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ext/Flows.kt, feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/viewmodel/AnnouncementViewModel.kt
- close #423 
- show ProgressBar when initial load
I used the source code below as reference.
- [collectIndexed](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/collect-indexed.html)
- [dropWhile](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/operators/Limit.kt#L34)
- [withIndex](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/operators/Transform.kt#L63)
- [map](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/operators/Transform.kt#L47)
- [debounce](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/operators/Delay.kt#L42)
Before | After
:--: | :--:
=> show ProgressBar when initial load

feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModelTest.kt
- close #154 
- Added test for SessionsViewModel
=> Add test for sessions view model

.ci/danger/static_analysis.Dangerfile, .ci/scripts/collect-ktlint-artifacts.bash, .circleci/config.yml, build.gradle
- N/A
- Danger has been commenting on issues that relate to only modified lines so far because issues order than that may annoy us for some reason. We already solved such issues, thanks to all contributors. So it's time to disable * dismiss_out_of_range_messages* option and report all issues.
- In addition, ktlint results should be saved to CircleCi Artifacts regardless of the fact above.
-
Before | After
:--: | :--:
=> Report all issues though Danger

ios-base/Gemfile.lock, ios-base/Makefile
- N/A
- Bump `Bundler` to latest version
- Add `xcode` command to Makefile (I'm not using `bundle install` with `--path vender/bundle`, but needs other steps in `init` command)
=> [iOS] `make xcode` command

model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SponsorCategory.kt
- close #606
- Use supporter instead of sponsors
-
Before | After
:--: | :--:
=> Fix supporter title

corecomponent/androidcomponent/src/main/res/values/strings.xml
None
There are many and many sessions, sponsors and contributors, so texts on the navigation should be plural form.
None
Before | After
:--: | :--:
=> make nouns plural form

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt, feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
None
Changed to switch filter text with binding data.
None
None
=> Use databinding for filter text

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/broadcastreceiver/NotificationBroadcastReceiver.kt
- Fix master build 🙏 
-
Before | After
:--: | :--:
=> Fix conflict

data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/RoomDatabase.kt
- withTransaction method handles Coroutine and Transaction appropriately. I think, withTransaction extension method better than current approach. 
- https://developer.android.com/reference/kotlin/androidx/room/package-summary#withtransaction
Before | After
:--: | :--:
=> [room database] use withTransaction androidx extension method

ios-base/.swiftlint.yml, ios-base/scripts/format.sh, ios-base/scripts/lint.sh
- None
- Same the title
- https://github.com/DroidKaigi/conference-app-2020/pull/447#discussion_r368300240
- https://realm.github.io/SwiftLint/file_header.html
=> [iOS] Enable file_header rule to ban header comments

ios-base/.swiftlint.yml, ios-base/DroidKaigi 2020/Session/Models/SessionDataProvider.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift, ios-base/DroidKaigi 2020/Session/Views/SessionPageViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SuggestView.swift, ios-base/DroidKaigi 2020/Sidebar/Views/SidebarViewController.swift, ios-base/DroidKaigi 2020/Sponsor/Views/SponsorViewController.swift
- none
- Fix code for lint
- `lint` was occurring in master branch by `swiftlint`.
- Change `swiftlint.yml`
- `swiftlint autocorrect` and `swiftformat` are not same format.
```
$ mint run realm/swiftlint swiftlint autocorrect
$ mint run swiftformat swiftformat DroidKaigi\ 2020
$ git status
On branch fix-for-lint
nothing to commit, working tree clean
```
-
Before | After
:--: | :--:
=> [iOS] Fix code for lint and change swiftlint setting

README.md, ios-base/.gitignore, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift, ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewController.swift, ios-base/DroidKaigi 2020/en.lproj/Localizable.strings, ios-base/DroidKaigi 2020/ja.lproj/Localizable.strings, ios-base/Makefile, ios-base/Mintfile, ios-base/swiftgen.yml
- N/A
- Introduce SwiftGen
- Use images safety
- Use color asset's color safety
- Ready for localizing
- [SwiftGen](https://github.com/SwiftGen/SwiftGen)
=> [iOS] Introduce SwiftGen

ios-base/DroidKaigi 2020/Session/Views/SessionPageViewController.swift
- close #661 
- I make Top-Left CornerRadius on SessionPageViewContoller::view
- [figma](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=4%3A2)
Before | After
:--: | :--:
=> [iOS] make top-left cornerRadius on SessionPageViewController

android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/di/AppModule.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/di/AppModuleBinds.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/AppInitializer.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/AppInitializers.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/AppInjector.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/CoilInitializer.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/EmojiInitializer.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/FirebaseFirestoreInitializer.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/FirestoreInitializer.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/ThemeInitializer.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/initializer/TimberInitializer.kt
- N/A
- More and more code is added to the application class. I'm suggest ways to improve this.
- You can wire initialization code using `Dagger IntoSet`.
- [chrisbanes/tivi ~ AppInitializers](https://github.com/chrisbanes/tivi/blob/master/app/src/main/java/app/tivi/appinitializers/AppInitializers.kt)
=> Modify, Initializer

.ci/Gemfile.lock
-
-
Before | After
:--: | :--:
=> Fix Dangerfile` file: undefined method `[]' for nil:NilClass

buildSrc/src/main/java/dependencies/Versions.kt
- Currently, our version name is 1.0.5. But it is 2019 version. So I make it 0.1.0. And I incremented version code for update.
-
Before | After
:--: | :--:
=> Version 0.1.0

feature/about/src/main/res/values/strings.xml
- close #679 
- Add about screen description for english
-
Before | After
:--: | :--:
| <img width="300" alt="スクリーンショット 2020-02-01 17 34 35" src="https://user-images.githubusercontent.com/50566499/73589405-4e659300-4519-11ea-8c89-be5affb0bcba.png">
=> Add about screen description for english

feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
- close #681 
- direct to http://www.association.droidkaigi.jp/privacy.html for Privacy Policy item
-
Before | After
:--: | :--:
=> Add navigation to privacy page

ios-base/Makefile, ios-base/scripts/bootstrap.sh
- N/A
- `make init` command
- Create shell script.
- Install all dependencies(e.g. `rbenv`, `mint`) if not installed.
- This may resolve #667 
- `xcode` may need `swiftgen`.
- `make` to run `xcode` target
- no link
=> [iOS] Fix Makefile

android-base/build.gradle.kts, android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt, android-base/src/main/java/io/github/droidkaigi/confsched2020/ui/CustomNavHostFragment.kt, build.gradle, buildSrc/src/main/java/dependencies/Dep.kt, corecomponent/androidcomponent/build.gradle, corecomponent/androidcomponent/src/main/res/navigation/navigation.xml, feature/contributor/src/main/AndroidManifest.xml, feature/preference/src/main/AndroidManifest.xml, feature/staff/src/main/AndroidManifest.xml, script/install_fakesplit
- close #334
- close #147
- Make on-demand dynamic feature module
- For debugging, use FakeInstallSplitManager
-
Run script
```
$ script/install_fakesplit
```
=> Make on-demand dynamic feature module

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ext/AppErrors.kt, corecomponent/androidcomponent/src/main/res/values-ja/strings.xml, corecomponent/androidcomponent/src/main/res/values/strings.xml, feature/system/src/main/java/io/github/droidkaigi/confsched2020/system/ui/viewmodel/SystemViewModel.kt, model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/AppError.kt
- close #571
- define external integrations error inherited AppError
- handle error no calendar integration
- #307
Before | After
:--: | :--:
=> Handle not found external integrations

feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModelTest.kt
- close #697 
- Add mock of `SessionAlarm` class
- Add verify test of `toggleRegister()`
=> Fix SessionsViewModelTest fail

feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt, feature/system/src/main/java/io/github/droidkaigi/confsched2020/system/ui/viewmodel/SystemViewModel.kt
- close #680 
- On about page, navigation to map when tapped access button.
-
Before | After
:--: | :--:
=> Navigation to map when tapped access

.circleci/config.yml, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/util/SessionAlarm.kt
- close #714 
- also close #706 
- Make the pull request CI failed when some of test tasks failed
- Disable offline mode when running test tasks on the pull request CI because some dependencies are not downloaded in `androidDependenciesExtra`
- Fix ktlint warnings in session module
No UI change
=> Make pull request CI failed when test tasks failed

data/repository/src/main/java/io/github/droidkaigi/confsched2020/data/repository/internal/DataSessionRepository.kt, feature/contributor/src/main/AndroidManifest.xml, feature/preference/src/main/AndroidManifest.xml, feature/session/src/main/res/font/noto_color_emoji_compat.xml, feature/session_survey/src/main/AndroidManifest.xml, feature/sponsor/src/main/AndroidManifest.xml, feature/staff/src/main/AndroidManifest.xml
- N/A
I'm apply Android Lint
- Empty Tag
- Unused XML schema declaration
- Nested lambda has shadowed implicit parameter
=> Apply Lint results 

feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/item/StaffItem.kt
- N/A
- Fix ktlint error
- This makes the "On release branch" workflow green
- https://github.com/DroidKaigi/conference-app-2020/actions?query=workflow%3A%22On+release+branch%22
- N/A
Before | After
:--: | :--:
=> Fix ktlint error

model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Room.kt
- API is applied!!!
-
Before | After
:--: | :--:
=> Fix exhibition room id

feature/session/src/main/res/layout/item_session.xml
-
-
Before | After
:--: | :--:
=> Fix session message layout

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/util/SessionAlarm.kt
=> Fix localed string room name

ios-base/DroidKaigi 2020/Common/Components/CollectionViewFlowLayoutLeftAlign.swift, ios-base/DroidKaigi 2020/Extentions/LocaledString+Ex.swift, ios-base/DroidKaigi 2020/Extentions/SearchResult+Ex.swift, ios-base/DroidKaigi 2020/Extentions/SessionContents+Ex.swift, ios-base/DroidKaigi 2020/Search/ViewModels/SearchViewModel.swift, ios-base/DroidKaigi 2020/Search/Views/Cells/ResultSpeakerCell.swift, ios-base/DroidKaigi 2020/Search/Views/Cells/ResultSpeakerCell.xib, ios-base/DroidKaigi 2020/Search/Views/SearchContentsDataSource.swift, ios-base/DroidKaigi 2020/Search/Views/SearchContentsViewController.swift, ios-base/DroidKaigi 2020/Search/Views/SearchSectionHeaderView.swift, ios-base/DroidKaigi 2020/Search/Views/SearchSectionHeaderView.xib, ios-base/DroidKaigi 2020/Search/Views/SearchViewController.swift, ios-base/DroidKaigi 2020/Session/Detail/SessionDetailViewController.swift, ios-base/DroidKaigi 2020/Session/Models/SessionDataProvider.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.xib, ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewController.swift, ios-base/DroidKaigi 2020/Session/Views/SessionViewDataSource.swift, ios-base/DroidKaigi 2020/en.lproj/Localizable.strings, ios-base/DroidKaigi 2020/ja.lproj/Localizable.strings
- close #492 
- Implement search view.
- bookmark sessions
- show bookmark session
- Remaining Tasks
- Prevent hiding behind keyboard.
-
Blank | Searched
:--: | :--:
Blank | Searched
:--: | :--:
=> [iOS] Implement search view

ios-base/DroidKaigi 2020/About/Views/AboutViewController.swift, ios-base/DroidKaigi 2020/Announcements/Views/AnnouncementsViewController.swift, ios-base/DroidKaigi 2020/Common/ContentTableViewController.swift, ios-base/DroidKaigi 2020/FloorMap/FloorMapViewController.swift, ios-base/DroidKaigi 2020/Sidebar/Views/SidebarViewController.swift, ios-base/DroidKaigi 2020/Sponsor/Views/SponsorViewController.swift
- close #734 , close #674
- Use common class to show menuButton and titleLabel in navigationBar.
-
=> [iOS]Use common class to show menuButton and titleLabel in navigationBar.

ios-base/DroidKaigi 2020/Search/Views/SearchContentsDataSource.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.xib, ios-base/DroidKaigi 2020/Session/Views/SessionViewDataSource.swift
- close #748 
- Changed to show message used when session location changes
-
Before | After
:--: | :--:
=> [iOS] Add session message to session cell

ios-base/DroidKaigi 2020/Search/Views/SearchContentsDataSource.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift, ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.xib, ios-base/DroidKaigi 2020/Session/Views/SessionViewDataSource.swift
- close #756
- I applied event item text design.
- figma : https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=1279%3A1339
Before | After
:--: | :--:
xxx | ![Feb-15-2020 00-07-38](https://user-images.githubusercontent.com/2672857/74542602-41b85480-4f87-11ea-8c4d-5d26c37b0003.gif)
=> [iOS] Add description label to SessionCell 

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt
- I forgot it 😇 
-
Before | After
:--: | :--:
=> Add entire_survey link

build.gradle, gradle/android-dynamic-module.gradle, gradle/android.gradle
-
- https://qiita.com/takahirom/items/cb9865b287dd6bab1007
Before | After
:--: | :--:
=> Fix release permission

buildSrc/src/main/java/dependencies/Versions.kt
- Gogogo
-
Before | After
:--: | :--:
=> Update version 1.0.0

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt
- I forgot to make the message invisible  when recyclerview
-
Before | After
:--: | :--:
=> Fix service session message cache problem

buildSrc/src/main/java/dependencies/Versions.kt
=> Upgrade patch version

README.md
…/issues/794
- close #794 
- add GooglePlay Link at Readme file.
Before | After
:--: | :--:
=> add GooglePlay Link at Readme file.

buildSrc/src/main/java/dependencies/Dep.kt, corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/BottomGestureSpace.kt, corecomponent/androidcomponent/src/main/res/values/dimens.xml, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt, feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/BottomSheetMotionLayout.kt, feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml, feature/session/src/main/res/layout/fragment_sessions.xml, feature/session/src/main/res/values/dimens.xml, feature/session/src/main/res/xml/fragment_bottom_sheet_sessions_scene.xml
- close #393
- Use MotionLayout for adapting gesture navigation
=> Bottom sheet animation with MotionLayout

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt, ios-base/DroidKaigi 2020/Sidebar/Views/SidebarViewController.swift
- none
- The title says everything.
- https://docs.google.com/forms/d/e/1FAIpQLSfQHIwT0lf-20tx5xgUFSm7PPy_EjD5lI8SHuxV3DHN4D9pkA/viewform
Android | iOS
:--: | :--:
=> Fix entire survey url

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt
- none
- The title says everything.
-
Before | After
:--: | :--:
=> Fix max line length for entire survey url

corecomponent/androidcomponent/src/main/res/values/styles.xml
- close #468 
Updates colorPrimary of selectedTextColor to colorSurface.
Before | After
:--: | :--:
=> Updates colorPrimary of selectedTextColor to colorSurface

buildSrc/src/main/java/dependencies/Dep.kt
- close #801 
- update gradle plugin version
=> fix update gradle plugin rc2 to rc3

buildSrc/src/main/java/dependencies/Dep.kt
- close Nothing()
- Suppress `const` modifier lint warning to `Dep.kt`
- none
Before | After
:--: | :--:
=> Suppress const modifier lint warning on Dep.kt

README.md
- I added detail for Kotlin MPP
-
Before | After
:--: | :--:
=> Remove TODO in README

.github/workflows/on_weekly.yml, android-base/build.gradle.kts, build.gradle, buildSrc/src/main/java/dependencies/Dep.kt
- https://plugin.releaseshub.com/
- I want to try this 😄
=> Add auto update dependencies

android-base/build.gradle.kts
- Title says everything
-
Before | After
:--: | :--:
=> Add repository info for releasesHub

android-base/build.gradle.kts
- The title says everything
-
Before | After
:--: | :--:
=> Add username and email for releaseHub

.github/workflows/on_weekly.yml
=> Use checkout@v2

.circleci/config.yml
- N/A
- This PR will remove danger-related ci steps. btw, the github token has already been removed from CircleCI.
-
=> Disable danger stuff
