README.md

Suffix is omitted in the official website.
https://droidkaigi.jp/2020/en/

Fix suffix of date on README

---

android-base/build.gradle
buildSrc/src/main/java/dependencies/Dep.kt

- close #149
- Update to LeakCanary 2.1.
- [Upgrading to LeakCanary 2 - LeakCanary](https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/)
- Added dependency on LeakCanary for only debug build.

Added dependency on LeakCanary

---

feature/session/src/main/res/layout/fragment_session_detail.xml

- close #181 
- add autoLink attribute in session detail
- https://github.com/DroidKaigi/conference-app-2020/blob/b6a92c302839309a53538807214aa7c967f96112/feature/session/src/main/res/layout/fragment_speaker.xml#L114
Before | After
:--: | :--:

add autoLink attribute in session detail

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/di/ApiComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/AppComponent.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/DbComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/DeviceComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/FirestoreComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/RepositoryComponentModule.kt
data/api/src/main/java/io/github/droidkaigi/confsched2020/data/api/ApiComponent.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/DbComponent.kt
data/device/src/main/java/io/github/droidkaigi/confsched2020/data/device/DeviceComponent.kt
data/firestore/src/main/java/io/github/droidkaigi/confsched2020/data/firestore/FirestoreComponent.kt
data/repository/src/main/java/io/github/droidkaigi/confsched2020/data/repository/RepositoryComponent.kt
feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/ContributorsFragment.kt
feature/preference/src/main/java/io/github/droidkaigi/confsched2020/preference/ui/PreferencesFragment.kt
feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/StaffsFragment.kt

- none
- Migrate from Dagger component builder to factory pattern introduced from Dagger 2.22
- Just call a single method to create components
- It is worth to avoid forgetting to call some builder methods
- https://github.com/google/dagger/releases/tag/dagger-2.22
- https://proandroiddev.com/dagger-and-the-shiny-new-component-factory-c2234fcae6b1
Before | After
:--: | :--:

Migrate Dagger component builder to factory pattern

---

README.md

- N/A
- Fix typo "Jetbrains"
- https://www.jetbrains.com/
N/A

Fix typo (Jetbrains to JetBrains)

---

feature/session/src/main/res/layout/item_session.xml
feature/session/src/main/res/layout/layout_speaker.xml

- close #140 
- adjusted touchable area of speaker view on session item 
Before | After
:--: | :--:

#140 adjusted touchable area of speaker view on session item

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt

- #119
- Add same margin as sessionTimeTextMarginTopInPx to position that after scrolling.
|Before|After|
|-|-|
|![droid0](https://user-images.githubusercontent.com/12192769/72365208-21ed0100-373b-11ea-8e47-8d711bf14c3e.gif)|![droid1](https://user-images.githubusercontent.com/12192769/72365235-2b766900-373b-11ea-8d57-eba6713090dd.gif)|

#119 Fix top start time text not to be moved by scrolling up

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt

- close #229
- OnClickListener is not recreated when the view is reused. So old speaker object is used.
- Always recreate OnClickListener lambda with new speaker object.
- Control flow cleanup

[SessionItem] Fix OnClickListener not updated on reuse of speaker views

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
feature/session/src/main/res/values-jp/strings.xml
feature/session/src/main/res/values/strings.xml

The query box was Japanese, and the result section headers were English,
both in direct strings.

Session search/filter box and result section headers are now localizable

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/SystemUiManager.kt

- close #121 
- `statusBarColors.isIndigoBackground` initial state is `false` and `config.isIndigoBackground` is false when you darktheme off. And then `if(field != value)` becomes false, it was not called `updateColors()` so status bar color disappeared.
-
See #121 before

Fixed status bar color not updating when Darktheme off

---

feature/session/src/main/res/layout/fragment_sessions.xml

- close #130 
- set `guideline_start` to `layout_constraintStart_toStartOf`
- set `0dp` to `wrap_content`
-
Before | After
:--: | :--:

Add filter margin start and end

---

feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/AnnouncementFragment.kt
feature/floormap/src/main/java/io/github/droidkaigi/confsched2020/floormap/ui/FloorMapFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session_survey/src/main/java/io/github/droidkaigi/confsched2020/session_survey/ui/SessionSurveyFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt

- N/A
- Fix wrong case
- LifeCycle -> Lifecycle
- Fix method's name (unify with other method's name)
- providesLifecycleLiveData -> providesLifecycleOwnerLiveData
- N/A
- N/A

Fix wrong case of method's name

---

data/api/src/iosMain/kotlinDebug/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt
data/api/src/iosMain/kotlinRelease/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt

- N/A
- Change ApiEndpoint for iOS from 2019 to 2020
- https://github.com/DroidKaigi/conference-app-2020/blob/master/data/api/build.gradle#L112-L118
- N/A

Change ApiEndpoint for iOS from 2019 to 2020

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt

- close #120 
- Set disable `clickable` labels at session detail screen
- N/A
Before | After
:--: | :--:

[SessionDetail] disable chip click

---

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/AutoClearedValue.kt
feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/AnnouncementFragment.kt
feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/ContributorsFragment.kt
feature/floormap/src/main/java/io/github/droidkaigi/confsched2020/floormap/ui/FloorMapFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session_survey/src/main/java/io/github/droidkaigi/confsched2020/session_survey/ui/SessionSurveyFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt
feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/StaffsFragment.kt

- close #153
- References to view, adapter, and more remain unintentionally when add a fragment to a backstack.
- Applied [AutoClearedValue](https://github.com/android/architecture-components-samples/blob/9826b59956eb93c9e627bdf16a19a1c8bc28ce14/GithubBrowserSample/app/src/main/java/com/android/example/github/util/AutoClearedValue.kt) solved this issue.
- AutoClearedValue is a delegated property that implements ReadWriteProperty. Set null in the onDestroy life cycle of viewLifecycleOwner.lifecycle.
- https://github.com/DroidKaigi/conference-app-2020/pull/230

Apply AutoCleardValue to Fragment member variables

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt

- close #310 
- subscribe `uiModel.expandFilterState` and toggle Button / ImageView
- subscribe `uiModel.expandFilterState` and hide session list when collapsed
- I Implemented based on #263 
Before | After
:--: | :--:

Toggle expand icon of BottomSheet sub header label on MYPLAN tab

---

feature/session/src/main/res/layout/fragment_speaker.xml

- close #316 
- Add tap feedback to speaker session name of fragment_speaker.xml
-
Before | After
:--: | :--:

Add tap feedback to speaker session name

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt

close https://github.com/DroidKaigi/conference-app-2020/issues/133
Hide keyboard when moved to other Fragment.
I used `onDestroyView()` of Fragment because implementation is short and simple.
It seems to work but I'm not sure (because it's first time to use this way honestly). Please check whether appropriate or not 🙏

Hide keyboard when moved to other Fragment

---

feature/session/src/main/res/layout/fragment_session_detail.xml

Sorry, I Forgot to add `android:lineSpacingExtra ` to a part of TextView :bow:
- close #306 
- I think we should increase the spacing between lines in whole textview.
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=21%3A395
- https://developer.android.com/reference/android/widget/TextView.html#attr_android:lineSpacingExtra
Before | After
:--: | :--:

A part of TextView padding between lines

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt

- close #326
- added processing to add `systemWindowInsetBottom` to padding
- 
After

add bottom margin myplan tab

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/ui/CustomNavHostFragment.kt
android-base/src/main/res/layout/activity_main.xml
corecomponent/androidcomponent/build.gradle
corecomponent/androidcomponent/proguard-rules-navigation.pro
corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/ui/ChromeCustomTabsNavigator.kt
corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
corecomponent/androidcomponent/src/main/res/values/attrs.xml
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/item/LargeSponsorItem.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/item/SponsorItem.kt
feature/system/build.gradle
feature/system/src/main/java/io/github/droidkaigi/confsched2020/system/ui/viewmodel/SystemViewModel.kt

- close #324
- Open sponsor URLs through navigation
- https://proandroiddev.com/add-chrome-custom-tabs-to-the-android-navigation-component-75092ce20c6a
Before | After
:--: | :--:

Open sponsor URLs through navigation

---

android-base/build.gradle
android-base/src/debug/java/io/github/droidkaigi/confsched2020/DebugApp.kt
build.gradle
buildSrc/src/main/java/dependencies/Dep.kt

- close #332 
- Replace to Firebase Crashlytics library. Thanks @takahirom 🙇
- https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android
Before | After
:--: | :--:

Replace Fabric Crashlytics library to Firebase

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/di/ApiComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/DbComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/DeviceComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/FirestoreComponentModule.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/RepositoryComponentModule.kt
data/api/src/main/java/io/github/droidkaigi/confsched2020/data/api/internal/ApiModule.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/DbModule.kt

- Close #195 
- As of Dagger 2.25.2, `@Module object` classes no longer need `@JvmStatic` on the provides methods, so removed them.
- But `@Module companion object` classes still need it (https://github.com/google/dagger/issues/1646).
- https://github.com/google/dagger/releases/tag/dagger-2.25.2
Before | After
:--: | :--:

Remove @JvmStatic annotations

---

data/repository/src/main/java/io/github/droidkaigi/confsched2020/data/repository/internal/mapper/SessionMappers.kt

- none
- Delete the definition of individual offset, and use common [TZ definition](https://github.com/DroidKaigi/conference-app-2020/blob/2078fc3/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/TimeZoneOffset.kt). 
To reduce the number of changes when changing offset.
- none
none

use common timezone offset definition

---

buildSrc/src/main/java/dependencies/Dep.kt
corecomponent/androidcomponent/build.gradle
corecomponent/androidtestcomponent/build.gradle
feature/about/build.gradle
feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
feature/announcement/build.gradle
feature/contributor/build.gradle
feature/preference/build.gradle
feature/session/build.gradle
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerItem.kt
feature/session_survey/build.gradle
feature/sponsor/build.gradle
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/item/LargeSponsorItem.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/item/SponsorItem.kt
feature/staff/build.gradle
feature/system/build.gradle

- N/A
- Updated versions about navigation component
- Deleted unused libraries
- If full kotlin project, we can use only ktx libraries
- To use `safe args kotlin`, generated codes are changed to kotlin codes.
- Try to use navigation method on click event for navigating to staffs
- What I was doing was the same as before...
- https://developer.android.com/guide/navigation/navigation-getting-started
- https://developer.android.com/guide/navigation/navigation-navigate
Generated codes
by Java | by Kotlin
:--: | :--:

Updated to use navigation component by Kotlin

---

feature/session/src/main/res/layout/fragment_session_detail.xml

- close #305
- Put progress bar center and outside of base layout view group in session details.
case1 | case2
:--:|:--:
case1 | case2
:--:|:--:

Improve position of progress bar in session details.

---

feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SearchSessionsViewModelTest.kt

https://github.com/DroidKaigi/conference-app-2020/issues/155
- Add SearchSessionsViewModel Unit Test.
- N/A
- N/A

Add ViewModel test for session search screen 

---

README.md

- close #330
- Add link to AutoClearedValue to README
- AutoClearedValue from Android Architecture Components samples
- [architecture\-components\-samples/AutoClearedValue\.kt at master · android/architecture\-components\-samples](https://github.com/android/architecture-components-samples/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/util/AutoClearedValue.kt)

Add link to AutoClearedValue

---

android-base/src/main/res/layout/activity_main.xml

- close #378
- Suppress warning "Use FragmentContainerView instead of fragment tag"

Add ignore attribute to fragment tag in activity_main.xml

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SearchResult.kt

fix SearchSessionFragment : remember query text, when come back after query searching
- close #348 
- Set(≒initialize) query text in `SearchSessionsFragment::onCreateOptionsMenu`.
(`SearchSessionsFragment::onCreateOptionsMenu`でクエリテキストの設定をしました。)
- Second arg of `searchView.setQuery()` is `false`. Because I think submit is unnecessary, In this case `searchResult` is remembered in `SearchSessionsViewModel`.
(`searchView.setQuery()`の第２引数は`false`にしています。この時検索結果はViewModelに覚えられていて、submitが不要と考えているためです。)
- none.
- none.
Please let me know if there are strange points in my code & PR.🙏🙏🙏
(変なところがあったら教えてください！🙏🙏🙏)

fix SearchSessionFragment : remember query text

---

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml

- close #396 
- Set `app:tint` to BottomSheet expand icon ImageView to see it easily when app running on dark theme
-
Pixel 3a emulator, API 28
Before | After
:--: | :--:

Tint BottomSheet expand icon to see it easily when app running on dark theme

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt

- close #394 
- The display conditions of EmptyView on My Plan depended on the number of speaker sessions added to favorites. 
- Simply changed to depend on the number of items added to favorites
-
Before | After
:--: | :--:

Fix display conditions issue of my plan's empty session view

---

feature/session/src/main/res/layout/fragment_bottom_sheet_favorite_session.xml

- close #406 
- related #396 
- Set `app:tint` to MY PLAN's BottomSheet expand icon ImageView to see it easily when app running on dark theme
- DAY1 and DAY2's BottomSheet expand icon had already fixed on #399 
-
Pixel 3a emulator, API 28
Before | After
:--: | :--:

Tint MY PLAN's BottomSheet expand icon to see it easily when app running on dark theme

---

corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerDetailItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerItem.kt
feature/session/src/main/res/layout/item_speaker.xml
feature/session/src/main/res/layout/layout_speaker.xml

- close #168
- Apply SharedElementTransition to speaker image
- Also I tried to apply "return shared element" for SpeakerFragment to SessionDetailFragment transition.
- It was difficult to apply return shared element to other transitions.
-
||Before | After
|---|:--: | :--:
|Main to Speaker|<img src="https://user-images.githubusercontent.com/32016001/72664660-d2ad1600-3a43-11ea-820b-a9ea8d2ab615.gif" width="300" /> | <img src="https://user-images.githubusercontent.com/32016001/72664450-5f0a0980-3a41-11ea-9675-45a0c86f82e7.gif" width="300" />
|Search to Speaker|<img src="https://user-images.githubusercontent.com/32016001/72664539-8b725580-3a42-11ea-93ee-9ab92baab357.gif" width="300" /> | <img src="https://user-images.githubusercontent.com/32016001/72664606-50245680-3a43-11ea-961f-ca962fd75f …

Use SharedElementTransition when transitioning to the Speaker screen

---

corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/color-night/speaker_name_session_detail.xml
feature/session/src/main/res/color/speaker_name_session_detail.xml
feature/session/src/main/res/layout/layout_speaker_session_detail.xml

- close #390 
- String localizing
- User icon sizing(60dp)
- Speaker name sizing(textAppearanceBody2)
- Should more intuitive tap feedback like speaker layout of day's session
-
Before | After
:--: | :--:

Apply speaker item's design in session detail screen

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/res/layout/fragment_bottom_sheet_favorite_session.xml

- close #397
- I changed the conditions for displaying the filter button.
- The filter button is displayed when (has filtered sessions || unfiltered) && close the filter.
-
Before | After
:--: | :--:

Fix: If filter hits on MyPlan page, filter button is shown

---

corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/DaggerFragment.kt
feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/AnnouncementFragment.kt
feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/ContributorsFragment.kt
feature/floormap/src/main/java/io/github/droidkaigi/confsched2020/floormap/ui/FloorMapFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetDaySessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetFavoriteSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session_survey/src/main/java/io/github/droidkaigi/confsched2020/session_survey/ui/SessionSurveyFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt
feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/StaffsFragment.kt

- none
- Specify layout resource on fragment constructor
- Now, the new constructor of Fragment is supplied to specify the layout. We can use it to inflate automatically on onCreateView.
- Original DaggerFragment doesn't support AndroidX yet. So, I re-implement it to apply Fragment of AndroidX.
- https://developer.android.com/reference/kotlin/androidx/fragment/app/Fragment?hl=en#%3Cinit%3E(kotlin.Int)
Before | After
:--: | :--:

Specify layout resource on constructor of Fragment

---

android-base/src/debug/res/values/strings.xml

- close #381 
- changed app name for debug 
- `DroidKaigi 2020` -> `DK2020 Debug`
※ I tried [easylauncher-gradle-plugin](https://github.com/akaita/easylauncher-gradle-plugin), but it doesn't yet support vector drawables, so I could not use it...
-
Before | After
:--: | :--:

Change app name for debug

---

data/api/build.gradle
gradle/android.gradle

- none
- Fix the following warning on build
```
build.gradle: API 'variant.getGenerateBuildConfig()' is obsolete and has been replaced with 'variant.getGenerateBuildConfigProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
```
- https://d.android.com/r/tools/task-configuration-avoidance

Fix gradle obsolete API warnings

---

corecomponent/androidcomponent/src/main/res/navigation/navigation.xml
corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
corecomponent/androidcomponent/src/main/res/values/strings.xml
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/drawable/ic_slide_24dp.xml
feature/session/src/main/res/drawable/ic_slide_light_blue_24dp.xml
feature/session/src/main/res/drawable/ic_video_24dp.xml
feature/session/src/main/res/drawable/ic_video_light_blue_24dp.xml
feature/session/src/main/res/layout/fragment_session_detail.xml
feature/session/src/main/res/values-jp/strings.xml
feature/session/src/main/res/values/strings.xml

- close https://github.com/DroidKaigi/conference-app-2020/issues/164
- Display a disabled link even if there is no material yet.
- Display a link if there is material.
Before | no material | no material dark | has material | has material dark 
:--: | :--: | :--: | :--: | :--:

Add presentation material to session detail

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt

- close #388
- Fix bug that options menu not shown when the screen is rotated.
- Investigate by the layout inspector, OptionsMenu was drawn. But, it's position was wrong.Call `invalidateOptionsMenu()` when `doOnApplyWindowInsets` then it was resolve.
Before | After
:--: | :--:

Fix options menu not shown when rotate

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerDetailItem.kt

- related to #168
- At https://github.com/DroidKaigi/conference-app-2020/pull/403, I call startPostponedEnterTransition when loading image is succeed.
- But I should call this method when loading image is failure. Otherwise we can not move to SpeakerFragment when (for example) network is off.
- Sorry I didn't notice 🙏 
- None
- None

Fix do not transition to SpeakerFragment when loading image is failure

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerSessionItem.kt
feature/session/src/main/res/layout/fragment_session_detail.xml
feature/session/src/main/res/layout/item_speaker_session.xml
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Session.kt

- close #419
- According to Fixme comment, time summary text was rewritten using binding adapter.
- But `timeSummary(Lang, TimezoneOffset)` method could not be bind to xml due to the Kotlin inline class.
- So added `timeSummary(Lang, Double)` method to avoid compilation errors.
- I want to know the correct way to resole this if you know it.
- https://github.com/DroidKaigi/conference-app-2020/issues/419#issuecomment-575976884

Implemented time summary text with binding adapter in session detail and speaker detail

---

feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/AnnouncementFragment.kt
feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/viewmodel/AnnouncementViewModel.kt

- close #124 
- ~Create `fun load()` in AnnoucementViewmodel.~
- ~Declare mutableLivedata for load function.~
- ~In `onViewCreated`, call `viewModel.load()` .~
- Create mutableLivedata that manage defaultLang.
- When `AnnoucementFragment#OnViewCreated()` called, update defaultLanguage.
- Nothing
Before | After
:--: | :--:

Use language change livedata for language change seamless load

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt
feature/session/src/main/res/drawable/favorite_button_selector.xml
feature/session/src/main/res/layout/item_session.xml

- close #122 
- Make favorite icon sync updated instead of async after update call.
- Utilized icon selector to update the favorite icon state.
- Minor cosmetic clean up.
-
Before | After
:--: | :--:

Make favorite icon state update right away when clicked

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt

- close #289 
- Fix expression to prevent `IndexOutOfBoundsException`
- Since  `index` and `position` are **usually** the same value, there is no problem if `index > 0` is true.(instead of `position > 0` is true)
- But there is an unexpected case that `index` and `position` have different values.
- this unexpected problem was fixed by any PR. (I can't find this PR)
- So I submit this PR, this PR may not be needed.

Fix "Crash when click on favorite button of first cell in sessions list"

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt
buildSrc/src/main/java/dependencies/Versions.kt

- close #454 
- change targetSdkVersion and compileSdkVersion to 29
- Because BuildCompat.isAtLeastQ became Deprecated, use Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q.
- ~change val to const val as in Packages.kt~
I tried to fix the two below, but I will revert if there is a problem !! 🙇

Use target sdk version 29 and compile sdk version 29

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailDescriptionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailMaterialItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailSpeakerItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailSpeakerSubtitleItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailTargetItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailTitleItem.kt

No
- Disable fade in effect in the SessionDetailFragment when click session favorite button.
- It is a degrade of #487
Before | After
:--: | :--:

Disable fade in effect in SessionDetailFragment when click session favorite button

---

feature/sponsor/src/main/res/layout/fragment_sponsors.xml

Sorry I forgot to create an issue 🙏 
- `fadingEdge` of SponsorFragment did not expand end to end of the screen.
- It caused by miss to set `clipToPadding` to false at the RecyclerView of `fragment_sponsor.xml`. 
(It's hard to see the difference...sorry.)
Before | After
:--: | :--:

Make fadingEdge of SponsorFragment expands end to end of the screen

---

ios-base/Configs/DroidKaigi 2020-Debug.xcconfig
ios-base/Configs/DroidKaigi 2020-Release.xcconfig

- close #514 
- iOS App cannot be buld after merging https://github.com/DroidKaigi/conference-app-2020/pull/509
- [iOS 向け .framework をビルドする](https://github.com/DroidKaigi/conference-app-2020/pull/509)

Fix iOS App not building

---

ios-base/DroidKaigi 2020/Info.plist

- close #499 
- Changed the colors of the font on the status bar to make it easy to see.
-
Before | After
:--: | :--:

iOS App Hardly see the status bar #499

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SpeakerDetailItem.kt

- close #313
- The speaker screen already had a placeholder icon. but it not had set that placeholder ImageView when starting the image loading by Coil.
Before | After
:--: | :--:
Before | After
:--: | :--:

fix a placeholder image is not shown when offline at the speaker screen.

---

ios-base/scripts/lint.sh

- N/A
- When we have some changes, iOS project build is failed by `Couldn't find executable "--path"`.  This can be fixed by specifying repository such as `realm/swiftlint` before `swiftlint` command.
- `$filename` is not enough path for lint. This is relative path such as `ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift`. It needs to absolute path. So I changed to `$SRCROOT/../$filename`
-

Fix iOS project build failed caused by SwiftLint

---

ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.xib

- close #531
- change SpeakersStackView height constraint, `greater than 0, priority=1000` to `equal 0, priority 250(Low)`
- if stack view is not empty, child view height becomes stack view"s height.(because child view's height priority is higher than stackview's)
- if stack view is empty, stackview's height constraint becomes highest priority.
- none
Before | After
:--: | :--:

iOS Fix SessionCell speakerStackView height when speaker is empty

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/SystemUiManager.kt

- close #463 
if I misunderstand this issue, close this PR 🙇
- update status bar color when navigation drawer offset is not zero (greater than zero)
Before | After
:--: | :--:

Change status bar color when slideOffset is not zero

---

ios-base/DroidKaigi 2020/Info.plist

- N/A
- iOS App can't access to api endpoint
- because endpoint becomes http
- side effect of this commit #533
- to fix this issue, I changed Info.plist.
```
2020-01-22 22:27:18.876334+0900 DroidKaigi 2020[98338:9425975] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
2020-01-22 22:27:18.876605+0900 DroidKaigi 2020[98338:9425975] Cannot start load of Task <94466D15-D501-457C-B2E3-696A004E3D18>.<1> since it does not conform to ATS policy
```
-

Fix iOS can't access to api endpoint

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt

- close #340 
- Close drawer when back button pressed.
- None
Before | After
:--: | :--:
- When filter is shown
Before | After
:--: | :--:

Close drawer when back button pressed

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt
feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml

- none
- CI was failed by `Danger`. But content of error was not commented.
- display error: `Danger has failed this build.  Found 3 errors.` on #440 
- I found error when run lint on local.
```
$ ./gradlew clean && ./gradlew lintDebug testDebugUnitTest ktlint --continue
$ JUNIT_TEST_RESULT_DIR=/tmp bundle exec --gemfile=.ci/Gemfile danger pr "https://github.com/DroidKaigi/conference-app-2020/pull/440" --dangerfile=".ci/danger/static_analysis.Dangerfile"
...
Results:
Errors:
Warnings:
```
- I committed `BottomSheetSessionsFragment.kt` without any code changes for failed. https://github.com/DroidKaigi/conference-app-2020/pull/544/commits/4f3b520ff4fcdceb6151c91a4ff93c6f28a6dff2
- CI is failed: https://circleci.com/gh/DroidKaigi/conference-app-2020/634?utm_campaign=vcs-integration-link&utm_m …

Fix failed ci `found 3 errors` by Danger

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt

- no issue but bug fix
- if there are over 2 sessions had same start time, time label is gone
Before | After
:--: | :--:

Fix time label is gone if there are over 2 sessions had same start time

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt

- close #520
- Even if peekHeight was changed, the height of BottomSheetBehavior was not recalculated, so it was recalculated.
- requestLayout() uses onLayoutChild() because the phenomenon was not resolved.
- To save computational resources, STATE_COLLAPSED has been added to work only for issues
-
Before | After
:--: | :--:

bottom sheet behavior request force update

---

feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/item/AnnouncementItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailDescriptionItem.kt

- none
Current color of "Read More" buttons are using "R.color.design_default_color_secondary" (this is secondary color of material component's light theme)
It's not same as colors of Figma design, and not consider Dark Theme.
I changed to use secondaryColor of DroidKaigi theme.
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=0%3A1
Before | After
:--: | :--:

Fix color of "read more" text button

---

.ci/.editorconfig
.editorconfig

- close #503
- Follow the expected behaviour that #503 noted. The reason why we need to do it is also described.
- To check the behaviour, I ran `./gradlew ktlintFormat` and no diffs are generated as expected.
-
Before | After
:--: | :--:

Added editorconfig to disable the ktlint rule for import ordering

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt

- close #553 
- Sometime session list is not shown
- Due to multiple calls of `TransitionManager.beginDelayedTransition()`
Before | After
:--: | :--:

Fix session list is not shown when collapse then expand quickly

---

ios-base/scripts/format.sh
ios-base/scripts/lint.sh

- None
- Linting and formatting deleted files raises an error, so this PR stop it
- https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203

Stop linting and formatting deleted files

---

android-base/build.gradle
android-base/src/debug/java/io/github/droidkaigi/confsched2020/DeeplinkTester.kt
android-base/src/debug/res/layout/dialog_deeplink.xml
android-base/src/debug/res/layout/plugin_deeplink.xml
android-base/src/debug/res/values/strings.xml
buildSrc/src/main/java/dependencies/Dep.kt

When you test deeplink, you input command like this.
I often forget it, so I want a easy way to test.
```
adb shell am start -a android.intent.action.VIEW -d "https://droidkaigi.jp/2019/announcement"
```
1. launch app
2. shake a device or tap a hyperion notification
3. tap 'Deeplink Tester' in hyperion menu
* I wrote code in [DeeplinkTester.kt][code_tester] because it's easy to dispose it
* [Add deeplink support #146](https://github.com/DroidKaigi/conference-app-2020/issues/146)
* [Fix #146 Add deep-link support Announcement #250](https://github.com/DroidKaigi/conference-app-2020/pull/250)
* [Hyperion-AndroidでAndroidアプリをデバッグしよう](https://qiita.com/takahirom/items/2f6557f945ddd7c5e074) (2020/01/22)
* [ダイアログ](https://developer.android.com/guide/topics/ui/dialogs?hl=ja) (2020/01/22) …

Add deeplink tester

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt
corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/Prefs.kt
corecomponent/androidcomponent/src/main/res/values-ja/strings.xml
corecomponent/androidcomponent/src/main/res/values-v29/strings.xml
corecomponent/androidcomponent/src/main/res/values/strings.xml
feature/preference/src/main/java/io/github/droidkaigi/confsched2020/preference/ui/PreferencesFragment.kt
feature/preference/src/main/java/io/github/droidkaigi/confsched2020/preference/ui/viewmodel/PreferenceViewModel.kt
feature/preference/src/main/res/xml/setting.xml
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/NightMode.kt

- close #466 close #560 
- Follow system and battery option for dark theme.
- Before once user switched dark theme in app, they no longer back to system dependent mode.
- Default value is "System default" (API 29 and above) or "When  battery saver is on" (API 28 and below).
- App become dark when system dark setting is on (API 29 and above) or battery saver is on (all).
- Selecting "Dark" or "Light" make app ignores both system dark setting and battery saver setting.
- If we put preference's string resource in preference module, `App` cannot reference it. On the other hands, if we put them in base module, preference fragment needs to use them as another R class while R class of preference xml is in preference package. ([I did latter](https://github.com/DroidKaigi/conference-app-2020/pull/5 …

More options for dark theme

---

feature/floormap/src/main/res/layout/fragment_floormap.xml

- close #568 
- make floormap clear enough under dark theme
Before | After
:--: | :--:

Floor map with dark theme

---

feature/announcement/src/main/res/layout/item_announcement.xml

- close #525 
- The TextView in announcement recyclerview analyzes link text, and it doesn't interpret html tag
-
Before | After
:--: | :--:

fix announcement link text

---

ios-base/DroidKaigi 2020/ApplicationScheme.swift
ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift

- N/A
- I replaced value of `surfaceColor` with `.white`. (Refer to [Android implementation](https://github.com/DroidKaigi/conference-app-2020/blob/master/corecomponent/androidcomponent/src/main/res/values/themes.xml#L25))
- And set `onSurfaceColor` to `.black`.
- (The reason for this change is that I want to use `surfaceColor` as `.white` in [Sponsor screen](https://github.com/DroidKaigi/conference-app-2020/issues/494))
- N/A
Before | After
:--: | :--:

[iOS] Replace value of surfaceColor

---

ios-base/Gemfile
ios-base/Gemfile.lock
ios-base/Makefile
ios-base/project.yml

- N/A
- Add configuration for testing with `DroidKaigi 2020Tests`
- `⌘+U` in Xcode will be enabled.
- Add `make test` command
When I made both unit test and UI test, it often failed and had no ideas😭.
For this reason, I didn't use UITest.

[iOS] Enable unit test

---

feature/staff/build.gradle

- close #591
- Coroutines dispatchers are changed when the staff module. So I fixed it
base
staff
-
Before | After
:--: | :--:

Delete test module use when not test

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModel.kt
feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Room.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionList.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionPage.kt

- #554 
- Add Event Tab for sessions and bind the data of the room named Exhibition that is included in the data of the list of Sessions.
- https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=1279%3A1339
Before | After
:--: | :--:

Add event tab for sessions

---

feature/sponsor/src/main/res/layout/item_sponsor.xml

- N/A
- UI design of [List Sponsor](https://www.figma.com/file/4r9becvhDy3GfXaXex8E8d/App?node-id=22%3A507) says `SUPPORTER` and `TECHNICAL SUPPORT` sponsors item height is `72dp`, but actually it is `112dp`.
- N/A
Before | After
:--: | :--:

Fix sponsor item height

---

feature/session/src/main/res/values/strings.xml

- close #579 
- I fixed filter_now value from "絞り込み中" to Filtering
-
Before | After
:--: | :--:

Fix filter_now to support English

---

ios-base/DroidKaigi 2020/AppDelegate.swift
ios-base/DroidKaigi 2020/Common/NavigationController.swift
ios-base/DroidKaigi 2020/Info.plist
ios-base/DroidKaigi 2020/SceneDelegate.swift
ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift

- N/A
- This app has both the dark screen and the bright screen with the status bar part. So I enabled view controller-based status bar appearance.
- [ステータスバーのスタイル(色)変更方法優先度 まとめ](https://qiita.com/ux_design_tokyo/items/8e62977b7609e68755c7)
Before | After
:--: | :--:
Before | After
:--: | :--:

[iOS] Enable view controller-based status bar appearance

---

corecomponent/androidcomponent/build.gradle

N/A
-  Removed duplicate dependencies
- in build.gradle(:corecomponent:androidcomponent), there are duplicate dependencies for `Dep.Kotlin.stdlibJvm`  and `Dep.AndroidX.liveDataKtx` .
- is it ok to leave dependency for `liveDataKtx` with `api` ?
N/A
N/A

Removed duplicate dependencies

---

feature/session/src/main/res/layout/item_session_detail_speaker.xml

Nothing
- We can tap all of the line of speaker in session detail, but ripple effect is only for speaker icon and name 
Nothing
Before | After
:--: | :--:

Expand ripple effect for speaker

---

ios-base/Makefile
ios-base/scripts/git-hooks/post-checkout

- N/A
iOS project is using XcodeGen.
When switching branch or rebase from origin/master and there is file addition/deletion,
we needs to re-run `xcodegen`.
This PR makes it doing automatically.
- [XcodeGenを導入してハマったこと](https://qiita.com/417_72ki/items/b23db0e26ae740d1132d#%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%82%92%E5%88%87%E3%82%8A%E6%9B%BF%E3%81%88%E3%82%8B%E9%9A%9B%E3%81%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%8C%E8%BF%BD%E5%8A%A0%E5%89%8A%E9%99%A4%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%A6%E3%82%82%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AB%E5%8F%8D%E6%98%A0%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84)

`post-checkout` for iOS project

---

ios-base/DroidKaigi 2020/AppDelegate.swift
ios-base/DroidKaigi 2020/SceneDelegate.swift
ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift

- N/A
- Using `barTintColor` is better than `backgroundColor` for `UINavigationBar`.
- [Swift4でナビゲーションバーの色を変更する](https://qiita.com/k0uhashi/items/0fb4a9e70f4fb11df2f7)
- [UINavigationBarの色がbarTintColorに設定した色よりも薄く表示されてしまう問題](https://qiita.com/haranicle/items/894f8e5aaf182f1e237f)
Before | After
:--: | :--:

[iOS] Use barTintColor instead of backgroundColor for UINavigationBar

---

model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionPage.kt

- #610 
- Added `AndroidParcelize` for subclasses of `SessionPage` because of Parcelize clash.
Perhaps it's no longer crashed.
- Device : Pixel 3a
- OS : 10.0
-
Before | After
:--: | :--:

Fix SessionPage parcelize crash

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt

- close #596 
- The cause of this bug is call `invalidateOptionsMenu()` in `toolbar.doOnApplyWindowInsets {}` when query text changed.
- So, changed place of call `invalidateOptionsMenu()` from `toolbar.doOnApplyWindowInsets {}`  to `toolbar.doOnLayout {}`
- We can use `toolbar.doOnNextLayout {}` insted of `toolbar.doOnLayout {}` and resolved too. But, I don't know which is better. 😥
Before | After
:--: | :--:

Fix search auto entered

---

feature/session/src/main/res/layout/item_session_detail_speaker.xml

- close #611
- We cannot replace to compound drawable, because the ImageView is used for navigation transition.
- I propose using ConstraintLayout for avoid the lint warning message.
-
Before | After
:--: | :--:

Fix layout structure for lint issue of UseCompoundDrawables

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/AppComponent.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/di/AppInjector.kt
corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/di/Injectable.kt
feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/AnnouncementFragment.kt
feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/ContributorsFragment.kt
feature/floormap/src/main/java/io/github/droidkaigi/confsched2020/floormap/ui/FloorMapFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session_survey/src/main/java/io/github/droidkaigi/confsched2020/session_survey/ui/SessionSurveyFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt
feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/StaffsFragment.kt

- close #608
- Add [AppInjector](https://github.com/android/architecture-components-samples/blob/e571c59603e8cfb8556af168c29c0c01c829e21c/GithubBrowserSample/app/src/main/java/com/android/example/github/di/AppInjector.kt) and replace `DaggerAppCompatActivity` and `DaggerFragment` to it for auto-injection
- Use [Fragment LayoutId constructor](https://developer.android.com/jetpack/androidx/releases/fragment#1.1.0) instead of `onCreateView` because We can now use `androidx.fragment.app.Fragment` as the super class for our Fragments
No UI change

Automate Dagger injection & Use Fragment LayoutId constructor

---

feature/contributor/build.gradle
feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/ContributorsFragment.kt
feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/viewmodel/ContributorsViewModel.kt
feature/contributor/src/main/res/layout/fragment_contributors.xml
feature/contributor/src/main/res/values-ja/strings.xml
feature/contributor/src/main/res/values/strings.xml

- No Issue filed
- Follow-up from #115 
- Allow the user to retry reloading the data when the API call fails.
Before:
- Problem 1: When no cache exists and the API call fails, there's no way to reload the Contributors screen unless you exit and re-enter the Contributors screen.
- Problem 2: The loading indicator gets dismissed as soon as the repository loads data from DB regardless of whether cache exists or not. The app then starts an API call which could make the user wait for some time on a blank screen without any loading indicator until the API call completes.
After:
- When the API call fails, if there's no cache to show any data, then show a retry button. If cache exists, then show the retry option on the snackbar while displaying the current data.
- Loading indicator continues to …

Add retry on Contributors screen

---

feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml

close #625
Prevent tapping under layout when tapping fragment_bottom_sheet_sessions.
None
Before | After
:--: | :--:

Prevent tapping of the layout under

---

model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionList.kt

- close #424 
`SessionsList.currentSessionIndex` had returned `0` in spite of the session dose not started.
Before | After
:--: | :--:

Use property 'shouldScroll'

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModel.kt

- close #152 
- Scroll to the current session, when tapping tab.
Before | After(After tapping a tab)
:--: | :--:

Scroll to current time session when tapping tab

---

feature/session/src/main/res/layout/item_session_detail_description.xml
feature/session/src/main/res/layout/item_session_detail_target.xml
feature/session/src/main/res/layout/item_session_detail_title.xml

- N/A
- I want to translate session's text from English to Japanese.
- Make following text selectable in session detail
- Title
- Description
- Target
- N/A
Before | After
:--: | :--:

Make session's text selectable

---

feature/contributor/src/main/java/io/github/droidkaigi/confsched2020/contributor/ui/ContributorsFragment.kt
feature/contributor/src/main/res/layout/fragment_contributors.xml
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt
feature/staff/src/main/java/io/github/droidkaigi/confsched2020/staff/ui/StaffsFragment.kt
feature/staff/src/main/res/layout/fragment_staffs.xml

None
Add padding to views that overlap the navigation bar when scroll to bottom in RecyclerView.
- Pixel3 (Emulator) API 29
Before | After
:--: | :--:

Update bottom padding for contributor/sponsor/staff fragment

---

buildSrc/src/main/java/dependencies/Dep.kt

- close #656
- Android Gradle Plugin updated to 3.6 RC2

Update Android Gradle Plugin

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt
buildSrc/src/main/java/dependencies/Dep.kt
feature/about/src/main/java/io/github/droidkaigi/confsched2020/about/ui/AboutFragment.kt
feature/announcement/src/main/java/io/github/droidkaigi/confsched2020/announcement/ui/AnnouncementFragment.kt
feature/floormap/src/main/java/io/github/droidkaigi/confsched2020/floormap/ui/FloorMapFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/MainSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session_survey/src/main/java/io/github/droidkaigi/confsched2020/session_survey/ui/SessionSurveyFragment.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/SponsorsFragment.kt

- Removes unnecessary both `@Module` and `@JvmStatic` from companion objects.
- https://github.com/google/dagger/releases/tag/dagger-2.26

Update Dagger to 2.26

---

model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionList.kt

- close #669
- Create day session list after remove event session list.
nothing
Before | After
:--: | :--:

Exclude event sessions from day sessions

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt
corecomponent/androidcomponent/src/main/res/drawable/ic_feedback_black_24dp.xml
corecomponent/androidcomponent/src/main/res/menu/menu_nav_drawer.xml
corecomponent/androidcomponent/src/main/res/navigation/navigation.xml

- close #652 
- Add the entire survey to the navigation drawer. At this point, go to https://google.com when you press it.
-
Before | After
:--: | :--:

Add the entire survey to the navigation drawer

---

ios-base/scripts/bootstrap.sh

- N/A
- `make init` is failed on using shell that installed by `Homebrew`.
```shell
> make init
Unsupported shell: /usr/local/bin/zsh
make: *** [init] Error 1
```
-

`make init` failed on using shell installed by Homebrew

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailDescriptionItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailMaterialItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailSpeakerSubtitleItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailTargetItem.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailTitleItem.kt
feature/sponsor/src/main/java/io/github/droidkaigi/confsched2020/sponsor/ui/item/DividerItem.kt

- close N/A
`com.xwray.groupie.Item.isSameAs` is this code.
```
/**
* Whether two item objects represent the same underlying data when compared using DiffUtil,
* even if there has been a change in that data.
* <p>
* The default implementation compares both view type and id.
*/
public boolean isSameAs(Item other) {
if (getLayout() != other.getLayout()) {
return false;
}
return getId() == other.getId();
}
```
`getLayout() != other.getLayout()` result is same as `other is HogeItem` result.
So I delete that methods.
And, `getId()` is following.
```
private static AtomicLong ID_COUNTER = new AtomicLong(0);
private final long id;
public Item() {
this(ID_COUNTER.decrementAndGet());
}
protected Item(long id) {
this.id = id;
}
/**
* If you don't specify an id, this id is an auto-generated unique …
```

[suggest]Remove isSameAs instead of Item.id

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SpeakerFragment.kt
feature/session/src/main/res/layout/fragment_speaker.xml

-  Fixed that long speaker description will not scroll up from under the navigation bar
1. Go to Speaker Detail which has long description.
2. Scroll the page to the bottom
Before | After
:--: | :--:

Fixed that long speaker description will not scroll up from under the navigation bar

---

android-base/src/main/java/io/github/droidkaigi/confsched2020/MainActivity.kt
android-base/src/main/java/io/github/droidkaigi/confsched2020/ui/widget/SystemUiManager.kt

- close #498
- When using a dark theme on Android9 or lower, set NavigationBar to a color with low transparency.
- Prepare LiveData in SystemUiManager in a form similar to the status bar, and change the color of the navigation bar according to the OS version when Context.isNightMode changes.
Before | After
:--: | :--:

Home button is difficult to see in dark Theme.

---

feature/about/src/main/res/layout/item_about_header.xml

- N/A
- Set `lineSpacingExtra` to `8sp` like other multi-line text components for readability.
Before | After
:--: | :--:

Adjust line spacing of the description in about page

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/BottomSheetSessionsFragment.kt

- related https://github.com/DroidKaigi/conference-app-2020/issues/117
- RecyclerView.consumePendingUpdateOperations () is executed when you scroll by hand, and scrollBy (0, 0) is an easy way to call it.
-
Before | After
:--: | :--:

Add workaround for fixing sessions are not displayed on Android 5.0

---

ios-base/DroidKaigi 2020/Session/Views/EventViewController.swift
ios-base/DroidKaigi 2020/Session/Views/EventViewController.xib
ios-base/DroidKaigi 2020/Session/Views/FilterViewController.swift
ios-base/DroidKaigi 2020/Session/Views/SessionPageViewController.swift

- #657 
- Add a blank event tab for the iOS app.
- I created a new SessionViewControllerType .event and adjust the raw number carefully.
- I created a new EventViewController because it's not Session and it doesn't have a filtering view.
Before | After
:--: | :--:

[iOS] Add blank event tab

---

.circleci/config.yml
.github/workflows/on_release_branch.yml
data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/internal/response/SessionResponseImpl.kt
data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/response/SessionResponse.kt
data/db/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/db/entity/LevelEntity.kt
data/db/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/db/entity/SessionEntity.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/CacheDatabase.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/entity/LevelEntityImpl.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/entity/SessionEntityImpl.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/entity/mapper/LevelDataMapperExt.kt
data/db/src/main/java/io/github/droidkaigi/confsched2020/data/db/internal/entity/mapper/SessionDataMapperExt.kt
data/repository/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/repository/ResponseToModelMapper.kt
data/repository/src/main/java/io/github/droidkaigi/confsched2020/data/repository/internal/DataSessionRepository.kt
data/repository/src/main/java/io/github/droidkaigi/confsched2020/data/repository/internal/mapper/LevelMapper.kt
data/repository/src/main/java/io/github/droidkaigi/confsched2020/data/repository/internal/mapper/SessionMappers.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt
feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModel.kt
feature/session/src/main/res/layout/fragment_sessions.xml
feature/session/src/main/res/values/strings.xml
feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/Dummies.kt
feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModelTest.kt
model/build.gradle
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/AudienceCategory.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Filters.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Level.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Session.kt
model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/SessionContents.kt
model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2020/model/FiltersTest.kt

- close #709 
- rename AudienceCategory to Level
- create member level to Session model
- create LevelEntity
- fix FilterTest
- rename AudienceCategory to Level
日本語でこの変更を行った理由と私の思いについて書かせてください．
まず，AudienceCategoryという名前は去年のものだと思いますが，今年はLevelということで，視聴者のレベルではなく，セッションそのもののレベルであり，これは，セッションそのものの特性を指していることから，すべてのAudienceCategoryと名のついたものをLevelという名前に変えさせていただきました．
その際，iOS側のクラスの名前も変わってしまうことになります（なるはずですよね？）が，iOSではまだフィルターは実装されておらず，変更の効く範囲だと思いますので，このようにさせていただきました．
また，セッションのエンティティに`levels`という要素が加わったことにより，キャッシュのデータベースが変更されました．この事により，アプリのストレージをクリアしないとアップデート時に機能しなくなりますが，マイグレーションの処理は書いていません．理由としては，このアプリはまだPlayStoreに上がっておらず，開発段階であり，開発者の皆さまがアプリを再インストールすることで使えるようになるならば，スピード感を優先してマイグレーションはつけなくて良いと判断したためです．
最後に，テストについてです．今回私がいじったのは`model`モジュールですが，このモジュールの`jvmTest`モジュールはなぜかテストとして認識されていませんでした．`model/build.gradle`を見 …

Fix level filters

---

model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2020/model/SessionListTest.kt

- close #594 
- Add test cases for SessionList
- Since I didn't know much of SessionList, I created test cases based on actual code. Please point out if there are test cases that are unnecessary.
N/A
N/A

Add SessionListTest

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/values-ja/strings.xml
feature/session/src/main/res/values/strings.xml

- close #719
- `ServiceSession.id` is not an integer.
- Stop converting to integer.
Crash when click share button in welcome talk detail.
Click share button
Share to Twitter
Open URL shared on Twitter

Crash when click share button in welcome talk detail

---

README.md

- N/A
- Fix wrong status badge URL
-
Before | After
:--: | :--:

Fix wrong status badge URL

---

corecomponent/androidcomponent/src/main/res/values-night/themes.xml

- N/A
- Add a style `Theme.DroidKaigi.ActionBar` to adapt license page to dark theme
- https://github.com/DroidKaigi/conference-app-2020/issues/713#issuecomment-582219857
- Thanks @clockvoid san for your report :)
Before | After
:--: | :--:
tested device: Pixel 3
OS version: 10

Add style Theme.DroidKaigi.ActionBar for dark theme

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt

- close #62 
The cause of this issue is that the BottomAppBar cannot calculate its height correctly in API level 21 environment.
So I added process to measure own size when #doOnNextLayout is called.
- N/A
| | Before | After
| :--: | :--: | :--:
| Nexus5 Android5.0 | <img src="https://user-images.githubusercontent.com/33515193/74086280-ab86b900-4ac4-11ea-9bf8-957df48e746d.png" width="320" /> | <img src="https://user-images.githubusercontent.com/33515193/74086250-74b0a300-4ac4-11ea-98ae-d304200ff70c.png" width="320" />

Fix a bug that the BottomAppBar is not close to the FAB

---

corecomponent/androidcomponent/build.gradle
corecomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2020/util/Prefs.kt

- close #739
- Fix deprecated PreferenceManager. The android.preference has been updated to androidx.preference.
- https://developer.android.com/reference/android/preference/package-summary
- https://developer.android.com/reference/androidx/preference/package-summary

Fix deprecated PreferenceManager.

---

ios-base/project.yml

- close N/A
ref: https://github.com/DroidKaigi/conference-app-2020/issues/747#issuecomment-583845508
- Add `Release` scheme for iOS project.
-
Debug | Release
:--: | :--:

[iOS]add release scheme and specify debug scheme

---

buildSrc/src/main/java/dependencies/Dep.kt

update library, that's all
nothing
- some library has already been old
- fragment-ktx 1.2.0 -> 1.2.1
https://developer.android.com/jetpack/androidx/releases/fragment?hl=en#version_121_3
- jetpack navigation 2.2.0 -> 2.2.1
https://developer.android.com/jetpack/androidx/releases/navigation?hl=en#version_221_3
- workmanager 2.3.0 -> 2.3.1
https://developer.android.com/jetpack/androidx/releases/work?hl=en#version_231_3
- ktor 1.3.0 -> 1.3.1
https://github.com/ktorio/ktor/releases/tag/1.3.1
- hyperion 0.9.25 -> 0.9.27
https://github.com/willowtreeapps/Hyperion-Android/releases/tag/v0.9.27
- coil 0.8.0 -> 0.9.5
https://github.com/coil-kt/coil/releases/tag/0.9.5
only coil has major update, but there is no problem
I checked on android app

update library version which have no breaking change

---

ios-base/DroidKaigi 2020/FloorMap/FloorMapViewController.swift

- `viewDidLoad()` method that must be called in A was called in `init()` , so it was fixed
- Before the fix,  `Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value `  [occurred in the following parts:](https://github.com/DroidKaigi/conference-app-2020/pull/773/files#diff-4bb5ebce785a29b29305cf99ad3c3338R33-R34)
```Swift
let width = imageView.image?.size.width
let height = imageView.image?.size.height
```
None
No UI changes.
Before | After
:--: | :--:

[iOS]Change call location of loadMap() 

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionItem.kt

none
Fixed a bug that the session title was not translated even if set english lang to device.
none
| Before | After
| :--: | :--:
| <img src="https://user-images.githubusercontent.com/33515193/74395475-c2c1ff80-4e52-11ea-9be7-9d9e8484fc9c.png" width="320" /> | <img src="https://user-images.githubusercontent.com/33515193/74395460-b50c7a00-4e52-11ea-97c7-9f4fa6d95667.png" width="320" />

Fix a bug that the session title is not translated

---

ios-base/DroidKaigi 2020/Announcements/Views/AnnouncementsViewController.xib
ios-base/DroidKaigi 2020/Session/Views/SessionViewController.xib

- unissued.
- Expand collection/tableview bottom edge to superview beyond safe area.
-
Before | After
:--: | :--:

[iOS] Expand collection/tableview bottom edge to superview beyond safe area

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt

- close #101
Set maxWidth to searchView.
Before | After
:--: | :--:
Before | After
:--: | :--:

Set maxWidth to searchView.

---

ios-base/DroidKaigi 2020/FloorMap/FloorMapViewController.swift

- close #770
- Cache images when loading floor map
- [Nuke - LRU Memory Cache](https://github.com/kean/Nuke/tree/master#lru-memory-cache)
No UI changes.
Before | After
:--: | :--:

[iOS]Cache images when loading floor map

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/item/SessionDetailDescriptionItem.kt

- N/A
- When open session detail screen and go to floor map by bottom app's menu, bottom app position is shifted.
-
Before | After
:--: | :--:

Fix bottom bar wrong position when reattached

---

feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionDetailFragment.kt
feature/session/src/main/res/layout/fragment_session_detail.xml

- close #751
This issue can be avoided by running "adapter.clear()" before "adapter.update(items)" in the setupSessionViews method of the SessionDetailFragment class.
When "adapter.clear()" is run, "notifyItemRangeInserted()" works.
When "adapter.clear()" is not run, "notifyItemRangeChanged()" works.

fix expand animation.

---

ios-base/DroidKaigi 2020/Session/Models/BookingSessionProvider.swift
ios-base/DroidKaigi 2020/Session/RealmEntity/Mapper/RealmToModelMapper.swift
ios-base/DroidKaigi 2020/Session/RealmEntity/SessionEntity.swift

- close #782 
- Thank you for your reporting, @nukka123!
- Add message member in SessionEntity.
- Add mapper function that maps message valuable in SessionEntity to SpeechSession.
- Add Realm migration behavior that in conjunction scheme version like the Android version app because of error message like `Binding error to behavior relay: Error Domain=io.realm Code=10 "Migration is required due to the following errors:`.
- Because of that, if the session favorited in the previous version, the upgraded version's session message is temporarily blank. To fix it, re-favoriting the session.
- Nothing
Before | After
:--: | :--:

Fix Speech Session message if favorited

---

ios-base/scripts/build_kotlin_modules.sh

- Fix error of `mkdir $SRCROOT/build` if build directory is already exists
```
mkdir: /Users/.../conference-app-2020/ios-base/build: File exists
```
-
Before | After
:--: | :--:

[iOS] Fix error if build directory is already exists

---

android-base/src/main/AndroidManifest.xml
data/api/build.gradle
data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/data/api/internal/KtorDroidKaigiApi.kt
data/api/src/iosMain/kotlinDebug/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt
data/api/src/iosMain/kotlinRelease/io/github/droidkaigi/confsched2020/data/api/internal/apiEndpoint.kt

- close #785 
- API_ENDPOINT change scheme from http to https
- adding last `/` to timetable api URL.
- delete `usesCleartextTraffic`
- marge target branch is `master` ok?

#785 Fix to use https connection

---

build.gradle
buildSrc/src/main/java/dependencies/Dep.kt
corecomponent/androidcomponent/build.gradle

- Update Navigation 2.3.0-alpha03
- Now, SNAPSHOT repository is not working.
-
Before | After
:--: | :--:

Update Navigation 2.3.0-alpha03

---

.circleci/config.yml
buildSrc/src/main/java/dependencies/Dep.kt

- close #713
- Update OSS licenses Gradle plugin 
- More libraries are listed than before!
- <https://developers.google.com/android/guides/releases#march_09_2020>
Before | After
:--: | :--:

Update oss-license-plugin to list more libraries

---

ios-base/DroidKaigi 2020/AppDelegate.swift
ios-base/DroidKaigi 2020/Extentions/UIApplication+Ex.swift
ios-base/DroidKaigi 2020/FloorMap/FloorMapViewController.swift
ios-base/DroidKaigi 2020/SceneDelegate.swift
ios-base/DroidKaigi 2020/Session/Views/Cells/SessionCell.swift

- close #778
- Cache speaker icon's image on timeline
- [Nuke - LRU Memory Cache](https://github.com/kean/Nuke/tree/master#lru-memory-cache)
No UI changes.
Before | After
:--: | :--:

[iOS] Cache speaker icon's image
